=== lvfe/web-service-java/Assignments/lab2/lab2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="sattype">
  <xs:sequence>
     <xs:element name="transponder" minOccurs="0" maxOccurs="unbounded">
 	 <xs:complexType>
		<xs:attribute name="frequency" type="xs:string"/>
		<xs:attribute name="symbol_rate" type="xs:string"/>
		<xs:attribute name="polarization" type="xs:string"/>
		<xs:attribute name="fec_inner" type="xs:string"/>
 	 </xs:complexType>
	 </xs:element>
	 </xs:sequence>
	 
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="flags" type="xs:string" fixed="1"/>
		<xs:attribute name="position" type="xs:string"/>
	</xs:complexType>

  <xs:element name="satellites">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sat" type="sattype" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lvfe/web-service-java/Assignments/lab2/lab2.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="lab2.xsl"?>
<satellites 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.w3school.com.cn lab2.xsd">

<sat name="Amazonas (61.0W)" flags="1" position="-610">
	<transponder frequency="3980000" symbol_rate="3330000" polarization="0" fec_inner="3"/>
	<transponder frequency="4137000" symbol_rate="3409000" polarization="0" fec_inner="3"/>
	<transponder frequency="10999000" symbol_rate="3410000" polarization="0" fec_inner="5"/>
	<transponder frequency="11084000" symbol_rate="2000000" polarization="1" fec_inner="3"/>
	<transponder frequency="11095000" symbol_rate="30000000" polarization="0" fec_inner="3"/>
	<transponder frequency="11108000" symbol_rate="2170000" polarization="1" fec_inner="3"/>
	<transponder frequency="11110000" symbol_rate="2307000" polarization="1" fec_inner="3"/>
	<transponder frequency="11860000" symbol_rate="20400000" polarization="1" fec_inner="3"/>
	<transponder frequency="11972000" symbol_rate="13021000" polarization="1" fec_inner="3"/>
	<transponder frequency="12132000" symbol_rate="30000000" polarization="0" fec_inner="3"/>
	<transponder frequency="12172000" symbol_rate="30000000" polarization="0" fec_inner="3"/>
	<transponder frequency="12510000" symbol_rate="6666000" polarization="1" fec_inner="5"/>
</sat>
<sat name="PAS9 (58.0W)" flags="1" position="-580">
<transponder frequency="3720000" symbol_rate="27700000" polarization="1" fec_inner="5"/>
<transponder frequency="3760000" symbol_rate="27690000" polarization="1" fec_inner="5"/>
<transponder frequency="3760000" symbol_rate="28500000" polarization="0" fec_inner="5"/>
<transponder frequency="3787000" symbol_rate="7407000" polarization="0" fec_inner="4"/>
</sat>
</satellites>
