=== lvfe/web-service-java/Assignments/lab1/lab1_2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">



<xs:complexType name="horseOf">
				<xs:sequence>
					<xs:element name="HorseName" type="xs:string"/>
					<xs:element name="Teamster">
							<xs:complexType> 
								<xs:sequence>
									<xs:element name="TeamsterName" type="xs:string"/>
									<xs:element name="TeamsterComment" type="xs:string" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType> 
						</xs:element>
					<xs:element name="HorseComment" type="xs:string" minOccurs="0"/>
				</xs:sequence>
			</xs:complexType>





  <xs:element name="Sport">
    <xs:complexType>
	<xs:sequence>
        <xs:element name="Event" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="EventName" type="xs:string"/>
					<xs:element name="Race" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="RaceNumber" type="xs:string"/>
								<xs:element name="RaceDistance" type="xs:string"/>
								<xs:element name="RaceComment" type="xs:string" minOccurs="0"/>
								<xs:element name="Horse" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
									<xs:complexContent>
									
										<xs:extension base="horseOf">
											<xs:attribute name="status" default="active">
											<xs:simpleType>
												<xs:restriction base="xs:string">
												<xs:enumeration value="active"/>
												<xs:enumeration value="cancelled"/>
												</xs:restriction>
											</xs:simpleType>
											</xs:attribute>
										</xs:extension>
								
									
									</xs:complexContent>	
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
			</xs:element>
		</xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lvfe/web-service-java/Assignments/lab1/lab1_2.xml
<?xml version="1.0"?>

<Sport
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.w3school.com.cn lab1_2.xsd">

	<Event>
		<EventName>Sports Meeting</EventName>
		
		<Race>
			<RaceNumber>No.1</RaceNumber>
			<RaceDistance>300m</RaceDistance> 
			<RaceComment>good!</RaceComment> 
			<Horse status="active">
				<HorseName>Mary</HorseName>
				<Teamster>
					<TeamsterName>red team </TeamsterName>
					<TeamsterComment>good </TeamsterComment>
				</Teamster>
			    <HorseComment>good</HorseComment>
			</Horse>
		</Race>

  	
	</Event>
</Sport>
